PROFILE_SOCIALS = [
    "bible",
    "eumw",
    "playgames",
    "anghami",
    "smule",
    "adidasrunning"
    "chess",
    # "fetch",
    # "loseit",
    # "fiton",
    # "plex",
    # "myspace",
    # "hole19",
    # "komoot",
    # "polarsteps",
    # "costarastrology",
    # "familylocator",
    # "pandora",
    # "mewe",
    # "zepeto",
]

SOCIALS = [
    "facebook",
    "instagram",
    "linkedin",
    "tgm",
    "twitter",
    "skype",
    "truecaller",
    "icq",
    "sporttracks",
    "runkeeper",
    "goodreads",
    "garminconnect",
    "whatsapp",
    "tiktok",
    "flickr",
    "fitbit",
    "duolingo",
    "adidas",
    "pulsstory",
    "gravatar",
    "foursquare",
    "vivino",
    "aboutme",
    "bitbucket",
    "apple",
    "interpol",
    "google",
    "dropbox",
    "youtube",
    "khanacademy",
    "strava",
    "medium",
    "notion",
    "wattpad",
    "scribd",
    "edx",
    "teamtreehouse",
    "datacamp",
    "academia",
    "scholar",
    "babelio",
    "wikipedia",
    "inkitt",
    "github",
    "yelp",
    "microsoft",
    "myfitnesspal",
    "eyecon",
    "bluesky",
    "cashapp",
    "etsy",
    "trello",
    "quora",
    "touchtunes",
    "mapmyrun",
] + PROFILE_SOCIALS
