from core.config import Settings as CoreSettings


class Settings(CoreSettings):
    VETRIC_FACEBOOK_API_CANDIDATES_LIMIT: int = 100
    VETRIC_FACEBOOK_API_CANDIDATE_POSTS_LIMIT: int = 100
    VETRIC_FACEBOOK_API_CANDIDATE_UPLOADED_MEDIA_LIMIT: int = 100
    VETRIC_FACEBOOK_API_CANDIDATE_PAGES_LIKED_LIMIT: int = 100
    VETRIC_FACEBOOK_API_CANDIDATE_FOLLOWING_LIMIT: int = 100
    VETRIC_FACEBOOK_API_CANDIDATE_FRIENDS_LIMIT: int = 100


settings = Settings()
