profile_picture_mapping = {
    "display_name": "displayName",
    "last_modified": "lastModified",
    "original_image": "originalImage",
    "photo_filter_edit_info": "photoFilterEditInfo",
}

geo_mapping = {
    "default_localized_name": "defaultLocalizedName",
}

location_mapping = {
    "auto_generated": "autoGenerated",
}

member_rich_content_mapping = {
    "last_modified": "lastModified",
}

position_mapping = {
    "company_name": "companyName",
    "end_month_year": "endMonthYear",
    "country_code": "countryCode",
    "region_code": "regionCode",
    "location_name": "locationName",
    "member_rich_contents": "memberRichContents",
    "start_month_year": "startMonthYear",
    "geo_position_location": "geoPositionLocation",
    "display_location_name": "displayLocationName",
}

certification_mapping = {
    "end_month_year": "endMonthYear",
    "license_number": "licenseNumber",
    "start_month_year": "startMonthYear",
}

education_mapping = {
    "degree_name": "degreeName",
    "end_month_year": "endMonthYear",
    "fields_of_study": "fieldsOfStudy",
    "fields_of_sudy_name": "fieldsOfStudyName",
    "member_rich_contents": "memberRichContents",
    "school_name": "schoolName",
    "start_month_year": "startMonthYear",
}

honor_mapping = {
    "issue_date": "issueDate",
}

organization_mapping = {
    "end_month_year": "endMonthYear",
    "start_month_year": "startMonthYear",
}

member_mapping = {
    "member_id": "memberId",
}

patent_mapping = {
    "application_number": "applicationNumber",
    "filling_state": "fillingState",
}

publication_mapping = {
    "publication_date": "date"
}

project_mapping = {
    "end_month_year": "endMonthYear",
    "single_date": "singleDate",
    "start_month_year": "startMonthYear",
}

volunteering_experience_mapping = {
    "company_name": "companyName",
    "end_month_year": "endMonthYear",
    "single_date": "singleDate",
    "start_month_year": "startMonthYear",
}

volunteering_interest_mapping = {
    "suppoorted_non_profits": "supportedNonProfits",
    "company_id": "companyId",
    "company_name": "companyName",
    "supported_predefined_causes": "supportedPredefinedCauses",
    "supported_user_defined_causes": "supportedUserDefinedCauses",
}
